# Generated by Django 4.0.3 on 2022-04-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_thumbnail',
            field=models.ImageField(default='default.png', upload_to='cars'),
        ),
    ]
