# Generated by Django 4.0.3 on 2022-04-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_book_file_alter_book_book_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_thumbnail',
            field=models.ImageField(default='default.PNG', upload_to='cars'),
        ),
    ]
