# Generated by Django 4.0.3 on 2022-05-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_seo_description_book_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.ImageField(default='default.png', upload_to='cars'),
        ),
    ]
