# Generated by Django 4.0.3 on 2022-05-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_summary',
            field=models.TextField(default='book summury', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
