# Generated by Django 4.0.3 on 2022-04-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_images',
            field=models.ImageField(default='default-car.png', upload_to='cars'),
        ),
    ]
