# Generated by Django 4.0.3 on 2022-04-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomo', '0002_property_property_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_images',
            field=models.ImageField(default='default.png', upload_to='cars'),
        ),
    ]
