# Generated by Django 4.0.3 on 2022-04-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomo', '0003_alter_property_property_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
