# Generated by Django 4.0.3 on 2022-04-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoecormeceapp', '0005_alter_products_product_img'),
        ('accomo', '0004_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='liker',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Likee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('like', 'like'), ('Liked', 'Liked')], default='Liked', max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomo.property')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Djangoecormeceapp.customeruser')),
            ],
        ),
    ]
