# Generated by Django 4.0.3 on 2022-04-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoecormeceapp', '0005_alter_products_product_img'),
        ('accomo', '0005_property_liker_likee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='liker',
        ),
        migrations.AddField(
            model_name='property',
            name='liker',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to='Djangoecormeceapp.customeruser'),
        ),
    ]
