# Generated by Django 4.0.3 on 2022-04-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoecormeceapp', '0005_alter_products_product_img'),
        ('accomo', '0006_remove_property_liker_property_liker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likee',
            new_name='Like',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='liker',
            new_name='liked',
        ),
    ]
