# Generated by Django 4.0.3 on 2022-04-25 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomo', '0008_alter_like_property_alter_like_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_veiw_count', to='accomo.property')),
            ],
        ),
        migrations.CreateModel(
            name='Property_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_img', models.ImageField(default='default-car.png', upload_to='cars')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='accomo.property')),
            ],
        ),
    ]
