# Generated by Django 4.0.3 on 2022-05-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomo', '0010_property_seo_description_property_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_images',
            name='property_img',
            field=models.ImageField(upload_to='cars'),
        ),
    ]
