# Generated by Django 4.0.3 on 2022-05-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='seo_description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='seo_title',
        ),
    ]
