# Generated by Django 4.0.3 on 2022-05-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_description_post_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Tradebay', max_length=200),
        ),
    ]
