# Generated by Django 4.0.3 on 2022-04-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoecormeceapp', '0002_products_liked_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='views',
        ),
        migrations.DeleteModel(
            name='IpAdress',
        ),
        migrations.AddField(
            model_name='productviewcount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_veiw_count', to='Djangoecormeceapp.products'),
        ),
    ]
