# Generated by Django 4.0.3 on 2022-04-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoecormeceapp', '0003_productviewcount_remove_products_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.ImageField(default='default.png', upload_to='cars'),
        ),
    ]
