# Generated by Django 4.0.3 on 2022-04-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoecormeceapp', '0004_alter_products_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.ImageField(default='default.PNG', upload_to='cars'),
        ),
    ]
